CREATE TABLE zava_product(
pid VARCHAR2(100) CONSTRAINT zava_pid_pk PRIMARY KEY,
pname VARCHAR2(90) NOT NULL,
descript VARCHAR2(3000),
category NUMBER,
price NUMBER,
stock NUMBER,
regdate DATE DEFAULT SYSDATE,
readcnt NUMBER,
mid VARCHAR2(100)
);
